### ISSUE TITLE
準備中ですか？

### ISSUE THREAD

**Issue by ghost** [itta611/ChokokuCAD#2]
8/8になってから、始まりません。。。

**Comment by itta611** [comment]
作品そのものは動くようですが、、、始まらないとはどういうことですか？

**Comment by ghost** [comment]
ず～っと、ロードの8/8のままです。
1/8　2/8　3/8　5/8　6/8　7/8　8/8　となって、
8/8から動きません。

**Comment by ghost** [comment]
環境情報：
Operation System = Windows10 insider preview 20H2
WWWebbrowser =  Chrome92(うぇぶれこ)
web filtering soft = i-フィルター6.0(正規ライセンス版)

**Comment by itta611** [comment]
なるほど、、
Chrome92なので、ECMAScriptのバージョンも良さそうですね...
コンソールにてエラーがあれば教えて下さい。

**Comment by itta611** [comment]
@tsumuri3 別のブラウザでも試していただけますか？

**Comment by ghost** [comment]
すみません。
iフィルターに規制されました。。。
